import type { CSSProperties } from "react"

export const ui = {
  page: {
    width: "min(1120px, calc(100% - 32px))",
    margin: "32px auto 48px",
    display: "grid",
    gap: "24px",
  } satisfies CSSProperties,
  toolbar: {
    display: "flex",
    justifyContent: "flex-start",
  } satisfies CSSProperties,
  addButton: {
    display: "inline-flex",
    alignItems: "center",
    gap: "10px",
    padding: "12px 18px",
    border: "1px solid #cbd5e1",
    borderRadius: "14px",
    background: "#ffffff",
    color: "#1e293b",
    fontSize: "16px",
    fontWeight: 700,
    boxShadow: "0 10px 30px rgba(15, 23, 42, 0.08)",
  } satisfies CSSProperties,
  icon: {
    width: "18px",
    height: "18px",
  } satisfies CSSProperties,
  listCard: {
    overflow: "hidden",
    border: "1px solid #e2e8f0",
    borderRadius: "22px",
    background: "#ffffff",
    boxShadow: "0 18px 40px rgba(15, 23, 42, 0.08)",
  } satisfies CSSProperties,
  table: {
    width: "100%",
    borderCollapse: "collapse",
  } satisfies CSSProperties,
  tableHead: {
    background: "linear-gradient(180deg, #f8fafc 0%, #f1f5f9 100%)",
  } satisfies CSSProperties,
  tableHeadCell: {
    padding: "18px 24px",
    color: "#475569",
    fontSize: "12px",
    fontWeight: 800,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    textAlign: "left",
  } satisfies CSSProperties,
  tableRow: {
    borderTop: "1px solid #e2e8f0",
  } satisfies CSSProperties,
  tableCell: {
    padding: "22px 24px",
    color: "#334155",
    fontSize: "16px",
  } satisfies CSSProperties,
  actions: {
    display: "flex",
    flexWrap: "wrap",
    gap: "12px",
  } satisfies CSSProperties,
  editButton: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    padding: "10px 14px",
    border: 0,
    borderRadius: "12px",
    background: "#eff6ff",
    color: "#1d4ed8",
    fontWeight: 700,
    fontSize: "14px",
  } satisfies CSSProperties,
  deleteButton: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    padding: "10px 14px",
    border: 0,
    borderRadius: "12px",
    background: "#fef2f2",
    color: "#dc2626",
    fontWeight: 700,
    fontSize: "14px",
  } satisfies CSSProperties,
  emptyState: {
    padding: "40px 24px",
    color: "#64748b",
    fontSize: "15px",
    textAlign: "center",
  } satisfies CSSProperties,
  modalOverlay: {
    position: "fixed",
    inset: 0,
    zIndex: 9999,
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "center",
    padding: "48px 16px",
    background: "rgba(2, 6, 23, 0.72)",
    backdropFilter: "blur(3px)",
  } satisfies CSSProperties,
  modalCard: {
    width: "min(760px, 100%)",
    borderRadius: "24px",
    background: "#ffffff",
    boxShadow: "0 30px 80px rgba(15, 23, 42, 0.28)",
    overflow: "hidden",
  } satisfies CSSProperties,
  modalHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "22px 28px",
    borderBottom: "1px solid #e2e8f0",
  } satisfies CSSProperties,
  modalTitle: {
    margin: 0,
    color: "#0f172a",
    fontSize: "32px",
    fontWeight: 800,
    lineHeight: 1.1,
  } satisfies CSSProperties,
  modalClose: {
    border: 0,
    background: "transparent",
    color: "#94a3b8",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  } satisfies CSSProperties,
  modalBody: {
    padding: "28px",
  } satisfies CSSProperties,
  form: {
    display: "grid",
    gap: "20px",
  } satisfies CSSProperties,
  fieldRow: {
    display: "grid",
    gridTemplateColumns: "180px minmax(0, 1fr)",
    gap: "18px",
    alignItems: "start",
  } satisfies CSSProperties,
  fieldLabel: {
    paddingTop: "12px",
    color: "#0f172a",
    fontSize: "16px",
    fontWeight: 700,
  } satisfies CSSProperties,
  fieldControl: {
    width: "100%",
    padding: "14px 16px",
    border: "1px solid #cbd5e1",
    borderRadius: "14px",
    background: "#ffffff",
    color: "#0f172a",
    fontSize: "16px",
    outline: "none",
  } satisfies CSSProperties,
  fieldError: {
    gridColumn: "2",
    borderRadius: "12px",
    background: "#fef2f2",
    color: "#b91c1c",
    padding: "10px 14px",
    fontSize: "14px",
    fontStyle: "italic",
  } satisfies CSSProperties,
  message: {
    minHeight: "20px",
    borderRadius: "12px",
    padding: "10px 14px",
    fontSize: "14px",
    fontStyle: "italic",
  } satisfies CSSProperties,
  messageError: {
    background: "#fef2f2",
    color: "#b91c1c",
  } satisfies CSSProperties,
  messageSuccess: {
    background: "#ecfdf5",
    color: "#047857",
  } satisfies CSSProperties,
  submitRow: {
    display: "flex",
    justifyContent: "flex-start",
  } satisfies CSSProperties,
  submitButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: "110px",
    padding: "12px 20px",
    border: 0,
    borderRadius: "14px",
    background: "linear-gradient(135deg, #2563eb 0%, #1d4ed8 100%)",
    color: "#ffffff",
    fontSize: "15px",
    fontWeight: 800,
    boxShadow: "0 16px 30px rgba(37, 99, 235, 0.22)",
  } satisfies CSSProperties,
} as const
